export const LOGIN_USER = "login/loginuser"
export const LOGIN_ERROR = "login/error"
export const LOGOUT = "login/logout"
export const REGISTRATE_USER = "registrate/registrate"
export const REGISTRATE_ERROR = "registrate/error"